
name: Build Test

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install meson and ninja
        run: sudo apt install meson ninja-build
      - name: Initialize submodules
        run: git submodule update --init --recursive

